# Generated by Django 5.1.4 on 2024-12-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_specialization_appointmentslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
