# Generated by Django 5.1.3 on 2024-12-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_bookedappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='client_pictures/'),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='lawyer_pictures/'),
        ),
    ]
