# Generated by Django 5.1.4 on 2024-12-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_lawyerprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
