# Generated by Django 5.1.4 on 2024-12-24 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_appointmentslot_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedappointment',
            name='booked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookedappointment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
