# Generated by Django 5.1.4 on 2024-12-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_bookedappointment_booked_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedappointment',
            name='booked_at',
        ),
        migrations.RemoveField(
            model_name='bookedappointment',
            name='payment_id',
        ),
    ]
